<?php
/**
 * Author: yorks
 * Date: 26.10.2019
 */

namespace app\modules\api\controllers;


use yii\db\ActiveQuery;
use yii\rest\ActiveController;

class CustomActiveController extends ActiveController
{
    /** @var ActiveQuery */
    protected $queryModel;
    protected $limit = 0;


    public function actions()
    {
        $actions = parent::actions();
        // customize the data provider preparation with the "prepareDataProvider()" method
        $actions['index']['prepareDataProvider'] = [$this, 'prepareDataProvider'];

        return $actions;
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $modelName = $this->modelClass;
        $this->queryModel = $modelName::find();
        $this->queryModel->where(['user_id' => \Yii::$app->user->id]);
    }

    public function prepareDataProvider()
    {
        $dataProvider = new \yii\data\ActiveDataProvider([
            'query' => $this->queryModel,
            'pagination' => ['pageSize' => $this->limit],
        ]);
        return $dataProvider;
    }
}