<?php
/**
 * Author: yorks
 * Date: 26.10.2019
 */

namespace app\modules\api\controllers;


use yii\rest\ActiveController;

/**
 * Class StatController
 * @package app\modules\api\controllers
 */
class StatController extends CustomActiveController
{

    public $modelClass = 'app\models\WordStat';


    /**
     * @return \yii\data\ActiveDataProvider
     */
    public function prepareDataProvider()
    {
        $this->limit = 7;
        return parent::prepareDataProvider(); // TODO: Change the autogenerated stub
    }
}
